$(document).ready(function(){
    $("h3").click(function(){
      $(".p").toggle();
    });
    $("h4").click(function(){
        $(".q").toggle();
    });
    $("h5").click(function(){
        $(".r").toggle();
    });
  });
  $(document).ready(function(){
    $(".work1").hover(function(){
    });
  });
